### ISSUE TITLE
The address wasn't understood

### ISSUE THREAD

**Issue by kiranshahi** [learn-co-curriculum/your-first-lab#3]
Firefox doesn't know how to open this address, because one of the following protocols (learn-ide) isn't associated with any program or is not allowed in this context.

    You might need to install other software to open this address.

URL: learn-ide://learn-ide/your-first-lab-cb-gh-000

**Comment by MAkcanca** [comment]
Forget about this really. They obviously never tested those. I'm running in Linux, they provided a deb package for me to download this. If i can install Learn IDE from deb package to the OS I'm currently using ( won't expose ), then I don't need that sh*t. Seriously. Check Udacity and several Youtube channels. Sentdex is a good python teacher if you wanna learn python. 

CHEERS

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 🙂
